### ISSUE TITLE
Fixar versão do node para o .trevis.yml

### ISSUE THREAD

**Issue by geison20** [stone-payments/node-global-identity#4]
Pensando em manter a estabilidade da lib, seria interessante fixar a versão do Node no Trevis?

**Comment by augusto-jm-amaral** [comment]
Manda bala rs

**Comment by vitorsilvalima** [comment]
No node e no package.json como você comentou. Mas lembrando que a versão tem que começar na 4

**Comment by augusto-jm-amaral** [comment]
@vitorsilvalima pq na 4?

**Comment by vitorsilvalima** [comment]
@augusto-jm-amaral  para fallback para uma versão antiga do node que seja lts. Me lembro que antes de fazermos a re-implementação da lib, ela estava suportando do node 4 pra cima. Então seria bom mantermos essa compatibilidade.

**Comment by augusto-jm-amaral** [comment]
Justo

**Comment by geison20** [comment]
Merged in production! 

close!
